# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AstroPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AstroPay

  target 'AstroPayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AstroPayUITests' do
    # Pods for testing
  end

end
